// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpyoG6Q2Bp1cu0Mwb9HweM5ACpKeepr_U',
    appId: '1:285199844278:web:b65ad02280038b10923717',
    messagingSenderId: '285199844278',
    projectId: 'chatty-pal-2',
    authDomain: 'chatty-pal-2.firebaseapp.com',
    storageBucket: 'chatty-pal-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6MauXs8kXoiUvnVwhA_j83ja0tHqT4gw',
    appId: '1:285199844278:android:56c6da9a7fa7fb58923717',
    messagingSenderId: '285199844278',
    projectId: 'chatty-pal-2',
    storageBucket: 'chatty-pal-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAubmMRJvSYhtOayuIt-DVG-YJJC5jODjU',
    appId: '1:285199844278:ios:7acd9620c3117436923717',
    messagingSenderId: '285199844278',
    projectId: 'chatty-pal-2',
    storageBucket: 'chatty-pal-2.appspot.com',
    iosClientId: '285199844278-98uggm6m6ha3rapu5i63c3q2faupie9p.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattyPal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAubmMRJvSYhtOayuIt-DVG-YJJC5jODjU',
    appId: '1:285199844278:ios:a915b35ce6e60fcd923717',
    messagingSenderId: '285199844278',
    projectId: 'chatty-pal-2',
    storageBucket: 'chatty-pal-2.appspot.com',
    iosBundleId: 'com.example.chattyPal.RunnerTests',
  );
}
